SolveTracker.Web/Models/Dashboard/DailySolveCountSummary.cs
namespace SolveTracker.Web.Models.Dashboard;

public class DailySolveCountSummary
{
    public int Index { get; set; }
    public string JudgeName { get; set; }
    public int SolveCount { get; set; }
}

SolveTracker.Web/Models/Dashboard/ProgrammerViewModel.cs
namespace SolveTracker.Web.Models.Dashboard;

public class ProgrammerViewModel
{
    public string DisplayName { get; set; }
    public int DailySolveCount { get; set; }
    public int TotalSolveCount { get; set; }
    public int WeeklySolveCount { get; set; }
    public List<DailySolveCountSummary> DailySolveCountSummary { get; set; }
    public List<TotalSolveCountSummary> TotalSolveCountSummary { get; set; }

    public ProgrammerViewModel()
    {
        DailySolveCountSummary = [];
        TotalSolveCountSummary = [];
    }
}

SolveTracker.Web/Models/Dashboard/TeacherViewModel.cs
namespace SolveTracker.Web.Models.Dashboard;

public class TeacherViewModel
{
    public string DisplayName { get; set; }
}

SolveTracker.Web/Models/Dashboard/TotalSolveCountSummary.cs
namespace SolveTracker.Web.Models.Dashboard;

public class TotalSolveCountSummary
{
    public int Index { get; set; }
    public string JudgeName { get; set; }
    public string OnlineJudgeHandle { get; set; }
    public string ProfileLink { get; set; }
    public int SolveCount { get; set; }
}

SolveTracker.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using SolveTracker.Application.Services.Dashboard;
using SolveTracker.Domain.Attributes;
using SolveTracker.Domain.Entities.Common;
using SolveTracker.Domain.Entities.Dashboard;
using SolveTracker.Web.Extensions.Attributes;
using SolveTracker.Web.Models.Common;
using SolveTracker.Web.Models.Dashboard;
using System.Data;
using System.Reflection;

namespace SolveTracker.Web.Controllers;

[RoleAuthorizeAttribute(UserRole.All)]
public class DashboardController(IDashboardService dashboardService) : Controller
{
    #region Public Methods

    public async Task<IActionResult> Index()
    {
        try
        {
            if (User.IsInRole("Programmer"))
            {
                ProgrammerViewModel model = await GetProgrammerViewModelAsync();
                return View("ProgrammerDashboard", model);
            }
            else if (User.IsInRole("Teacher"))
            {
                TeacherViewModel model = await GetTeacherViewModelAsync();
                return View("TeacherDashboard", model);
            }

            return View("~/Views/Common/AccessDenied.cshtml", null);
        }
        catch (Exception)
        {
            ErrorViewModel errorViewModel = new();
            return View("Error", errorViewModel);
        }
    }

    #endregion

    #region Private Methods

    private async Task<ProgrammerViewModel> GetProgrammerViewModelAsync()
    {
        OnlineJudgeHandle onlineJudgeHandle = await dashboardService.GetOnlineJudgeHandleAsync();
        OnlineJudgeProfileLink onlineJudgeProfileLink = await dashboardService.GetOnlineJudgeProfileLinkAsync();
        
        int weeklySolveCount = await dashboardService.GetWeeklySolveCountAsync();
        SolveCountSummary dailySolveCountSummary = await dashboardService.GetDailySolveCountSummaryAsync();
        SolveCountSummary totalSolveCountSummary = await dashboardService.GetTotalSolveCountSummaryAsync();

        List<DailySolveCountSummary> formattedDailySolveCountSummary = GetFormattedDailySolveCountSummary(dailySolveCountSummary);
        List<TotalSolveCountSummary> formattedTotalSolveCountSummary = GetFormattedTotalSolveCountSummary(totalSolveCountSummary, onlineJudgeHandle, onlineJudgeProfileLink);

        ProgrammerViewModel model = new()
        {
            DisplayName = User.Identity.Name,
            DailySolveCount = dailySolveCountSummary.Total,
            WeeklySolveCount = weeklySolveCount,
            TotalSolveCount = totalSolveCountSummary.Total,
            DailySolveCountSummary = formattedDailySolveCountSummary,
            TotalSolveCountSummary = formattedTotalSolveCountSummary,
        };

        return model;
    }

    private async Task<TeacherViewModel> GetTeacherViewModelAsync()
    {
        await Task.Delay(100);
        TeacherViewModel model = new()
        {
            DisplayName = User.Identity.Name,
        };

        return model;
    }

    private static List<DailySolveCountSummary> GetFormattedDailySolveCountSummary(SolveCountSummary summary)
    {
        int index = 1;
        List<DailySolveCountSummary> result = [];
        IEnumerable<PropertyInfo> summaryProperties = summary
                .GetType()
                .GetProperties()
                .Where(property => property.Name != "Total");

        foreach (PropertyInfo property in summaryProperties)
        {
            int solveCount = (int)property.GetValue(summary);
            if (solveCount == 0)
            {
                continue;
            }

            OnlineJudgeInfoAttribute attr = property.GetCustomAttribute<OnlineJudgeInfoAttribute>(false);
            string judgeName = attr.Name;

            result.Add(new DailySolveCountSummary
            {
                Index = index,
                JudgeName = judgeName,
                SolveCount = solveCount
            });

            index++;
        }

        return result;
    }

    private static List<TotalSolveCountSummary> GetFormattedTotalSolveCountSummary(SolveCountSummary summary, OnlineJudgeHandle onlineJudgeHandle, OnlineJudgeProfileLink onlineJudgeProfileLink)
    {
        int index = 1;
        List<TotalSolveCountSummary> result = [];
        IEnumerable<PropertyInfo> summaryProperties = summary
                .GetType()
                .GetProperties()
                .Where(property => property.Name != "Total");

        foreach (PropertyInfo property in summaryProperties)
        {
            int solveCount = (int)property.GetValue(summary);
            if (solveCount == 0)
            {
                continue;
            }

            OnlineJudgeInfoAttribute attr = property.GetCustomAttribute<OnlineJudgeInfoAttribute>(false);
            string judgeName = attr.Name;

            string handle = (string)onlineJudgeHandle
                .GetType()
                .GetProperties()
                .Where(property => property.GetCustomAttribute<OnlineJudgeInfoAttribute>(false).Name == judgeName)
                .FirstOrDefault()
                ?.GetValue(onlineJudgeHandle);

            string profileLink = (string)onlineJudgeProfileLink
                .GetType()
                .GetProperties()
                .Where(property => property.GetCustomAttribute<OnlineJudgeInfoAttribute>(false).Name == judgeName)
                .FirstOrDefault()
                ?.GetValue(onlineJudgeProfileLink);

            result.Add(new TotalSolveCountSummary
            {
                Index = index,
                JudgeName = judgeName,
                OnlineJudgeHandle = handle,
                ProfileLink = profileLink,
                SolveCount = solveCount
            });

            index++;
        }

        return result;
    }

    #endregion
}

SolveTracker.Web/Controllers/ProgrammersController.cs
using Microsoft.AspNetCore.Mvc;
using SolveTracker.Domain.Entities.Common;
using SolveTracker.Web.Extensions.Attributes;

namespace SolveTracker.Web.Controllers;

public class ProgrammersController : Controller
{
    [RoleAuthorize(UserRole.Teacher)]
    public IActionResult Index()
    {
        return View();
    }
}

SolveTracker.Web/Views/Dashboard/ProgrammerDashboard.cshtml
@model SolveTracker.Web.Models.Dashboard.ProgrammerViewModel;

<div id="dashboardContainer" class="w-75 mx-auto">
    <div class="greeting-section card p-4 my-3 rounded shadow-sm border-0">
        <h3>Good afternoon, @Model.DisplayName!</h3>
        <div class="text-secondary">Welcome back to your SolveTracker dashboard.</div>
    </div>
    
    <div class="solve-stats-section card p-4 my-3 rounded shadow-sm border-0">
        <div>
            <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "DailyLog")'">Add Log</button>
            <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "Notification")'">Notification</button>
        </div>
    </div>

    <div class="solve-stats-section card p-4 my-3 rounded shadow-sm border-0">
        <div class="row text-center">
            <div class="col-md-4 border-end">
                <span class="fw-bold fs-2 text-success">@Model.DailySolveCount</span>
                <div class="text-secondary">problems solved today.</div>
            </div>
            <div class="col-md-4 border-end">
                <span class="fw-bold fs-2 text-success">@Model.WeeklySolveCount</span>
                <div class="text-secondary">problems solved in the last week.</div>
            </div>
            <div class="col-md-4">
                <span class="fw-bold fs-2 text-success">@Model.TotalSolveCount</span>
                <div class="text-secondary">problems solved in total!</div>
            </div>
        </div>
    </div>

    <div class="summary-section card p-4 my-3 rounded shadow-sm border-0">
        <div class="row">
            <div class="daily-solve-summary-section col-md-6 border-end">
                <h5>Daily Solve Summary</h5>
                <div class="border-bottom mb-3"></div>
                <div class="text-secondary text-center @(Model.DailySolveCount == 0 ? "d-block" : "d-none")">
                    No problem solved today
                </div>
                <div class="max-vh-50 overflow-auto @(Model.DailySolveCount == 0 ? "d-none" : "d-block")">
                    <table class="table table-striped table-borderless">
                        <thead class="table-success sticky-top">
                            <tr>
                                <th>#</th>
                                <th>Judge</th>
                                <th class="text-center">Solved</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var summary in Model.DailySolveCountSummary)
                            {
                                <tr>
                                    <td>@summary.Index.</td>
                                    <td>@summary.JudgeName</td>
                                    <td class="text-center">@summary.SolveCount</td>
                                </tr>
                            }
                    </table>
                </div>
            </div>
            <div class="total-solve-summary-section col-md-6">
                <h5>Total Solve Summary</h5>
                <div class="border-bottom mb-3"></div>
                <div class="text-secondary fs-6 d-none text-center">No problem solved in any online judge</div>
                <div class="d-block max-vh-50 overflow-auto">
                    <table class="table table-striped table-borderless">
                        <thead class="table-success sticky-top">
                            <tr>
                                <th>#</th>
                                <th>Judge</th>
                                <th>Handle</th>
                                <th class="text-center">Solved</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var summary in Model.TotalSolveCountSummary)
                            {
                                <tr>
                                    <td>@summary.Index.</td>
                                    <td>@summary.JudgeName</td>
                                    <td><a href="@summary.ProfileLink" target="_blank" class="text-decoration-none">@summary.OnlineJudgeHandle</a></td>
                                    <td class="text-center">@summary.SolveCount</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

SolveTracker.Web/Views/Dashboard/TeacherDashboard.cshtml
@model SolveTracker.Web.Models.Dashboard.TeacherViewModel;

<div id="dashboardContainer" class="w-75 mx-auto">
    <div class="greeting-section card p-4 my-3 rounded shadow-sm border-0">
        <h3>Good afternoon, @Model.DisplayName!</h3>
        <div class="text-secondary">Welcome back to your SolveTracker dashboard.</div>
    </div>

    <div class="solve-stats-section card p-4 my-3 rounded shadow-sm border-0">
        <p>The teacher dashboard section is under development</p>
        <div>
            <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "Programmers")'">Programmers</button>
            <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "Mentors")'">Mentors</button>
            <button class="btn btn-success" onclick="window.location.href='@Url.Action("Index", "Notification")'">Notification</button>
        </div>
    </div>

</div>